# Generated by Django 4.2.1 on 2023-05-05 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('value', models.TextField()),
            ],
            options={
                'db_table': 'settings',
            },
        ),
    ]
