# Generated by Django 4.2.1 on 2023-05-05 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradecopier', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='copier_accounts',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('UserID', models.IntegerField()),
                ('AccountNumber', models.CharField(max_length=50)),
                ('BrokerName', models.CharField(max_length=50)),
                ('Token', models.CharField(max_length=255)),
                ('Status', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='copier_logs',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('AccountID', models.IntegerField()),
                ('OrderID', models.IntegerField()),
                ('LogTime', models.DateTimeField(auto_now_add=True)),
                ('Message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='copier_orders',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('AccountID', models.IntegerField()),
                ('OrderID', models.IntegerField()),
                ('Symbol', models.CharField(max_length=50)),
                ('Type', models.CharField(max_length=10)),
                ('Volume', models.FloatField()),
                ('OpenTime', models.DateTimeField()),
                ('OpenPrice', models.FloatField()),
                ('SL', models.FloatField()),
                ('TP', models.FloatField()),
                ('CloseTime', models.DateTimeField(null=True)),
                ('ClosePrice', models.FloatField(null=True)),
                ('Commission', models.FloatField()),
                ('Swap', models.FloatField()),
                ('Profit', models.FloatField()),
                ('Status', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='copier_users',
            fields=[
                ('UserID', models.AutoField(primary_key=True, serialize=False)),
                ('FirstName', models.CharField(max_length=50)),
                ('LastName', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('Password', models.CharField(max_length=255)),
                ('Phone', models.CharField(max_length=20)),
                ('Status', models.CharField(max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='Settings',
        ),
    ]
